obj-$(CONFIG_ARCH_MESON64_ODROIDC2) += odroid-sysfs.o
obj-$(CONFIG_ARCH_MESON64_ODROIDC2) += odroid-battery.o
obj-$(CONFIG_ODROID_USBIO_SENSOR)     += odroid-usbio.o
odroid-usbio-y := odroid-usbio-sensor.o odroid-usbio-mouse.o odroid-usbio-keypad.o odroid-usbio-setup.o
