obj-$(CONFIG_MACH_MESON8B_ODROIDC) += odroid-sysfs.o
obj-$(CONFIG_MACH_MESON8B_ODROIDC) += odroid-battery.o
obj-$(CONFIG_ODROID_USBIO_SENSOR)     += odroid-usbio.o
odroid-usbio-y := odroid-usbio-sensor.o odroid-usbio-mouse.o odroid-usbio-keypad.o odroid-usbio-setup.o
obj-$(CONFIG_MACH_MESON8B_ODROIDC) += odroid-gpiomem.o
